---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: aws-prepare-get
  - name: pcfawsops-terraform-state-get
  - name: tool-om
  - name: tool-om-beta
run:
  path: aws-prepare-get/ci/scripts/config-director.sh
